/* Experiencia interactiva, sin dependencias. Personalizá carta, fotos y audios aquí. */
document.addEventListener('DOMContentLoaded',()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const scenes=$$('.scene');const text='Hoy no solo celebramos un año más de tu vida; celebramos la suerte enorme de que estés en este mundo. Gracias por cada charla, cada abrazo, cada risa hasta que nos dolió la panza y por estar incluso cuando no hacen falta palabras.\n\nDeseo que este nuevo capítulo te devuelva multiplicado todo lo lindo que regalás. Que nunca te falten motivos para soñar, personas para celebrar y momentos que te hagan sentir tan querida como sos.\n\nTe quiero infinitamente. Feliz cumpleaños, hermanita.';let petals,frame;// El video se dibuja en Canvas y elimina el color uniforme del fondo (chroma key).
const video=$('#birdVideo'), birdCanvas=$('#birdCanvas'), birdCtx=birdCanvas.getContext('2d',{willReadFrequently:true});
video.addEventListener('loadeddata',()=>{function renderBird(){if(video.readyState>=2){const w=video.videoWidth,h=video.videoHeight;if(birdCanvas.width!==w){birdCanvas.width=w;birdCanvas.height=h}birdCtx.drawImage(video,0,0,w,h);const img=birdCtx.getImageData(0,0,w,h),d=img.data;let rr=0,gg=0,bb=0,count=0;for(let y=0;y<h;y+=Math.max(1,Math.floor(h/18)))for(let x=0;x<w;x+=Math.max(1,Math.floor(w/18))){if(x<w*.12||x>w*.88||y<h*.12||y>h*.88){let k=(y*w+x)*4;rr+=d[k];gg+=d[k+1];bb+=d[k+2];count++}}rr/=count;gg/=count;bb/=count;for(let k=0;k<d.length;k+=4){let distance=Math.hypot(d[k]-rr,d[k+1]-gg,d[k+2]-bb);if(d[k]<62&&d[k+1]<62&&d[k+2]<62)d[k+3]=0;else if(distance<92)d[k+3]=Math.max(0,(distance-18)/74*255)}birdCtx.putImageData(img,0,0);requestAnimationFrame(renderBird)} }renderBird()});
function show(id){scenes.forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo(0,0)}function play(x){x.play().catch(()=>{})}$('#start').onclick=()=>{play($('#music'));show('#flight');flight()};
function flight(){
  const scene=$('#flight'), bird=$('#bird'), hint=$('#flightHint'), next=$('#letterButton');
  const phrases=['❤️ Te quiero','🌸 Sos la mejor','✨ Gracias por existir','💕 Gracias por estar','🌷 Nunca cambies','🌼 Mi mejor amiga','💖 Sos increíble','🌺 Feliz cumpleaños','💝 Siempre voy a estar'];
  let found=0, dragging=false, offsetX=0, offsetY=0, startX=0, startY=0;
  const place=(x,y)=>{const r=scene.getBoundingClientRect(),b=bird.getBoundingClientRect();const left=Math.max(0,Math.min(x,r.width-b.width)),top=Math.max(0,Math.min(y,r.height-b.height));bird.style.transition='transform .14s ease-out';bird.style.transform=`translate(${left}px,${top}px)`;};
  const centre=()=>{const r=scene.getBoundingClientRect(),b=bird.getBoundingClientRect();place((r.width-b.width)/2,(r.height-b.height)/2.1)};
  centre();
  bird.onpointerdown=e=>{if(found===phrases.length)return;dragging=true;bird.setPointerCapture(e.pointerId);const b=bird.getBoundingClientRect();offsetX=e.clientX-b.left;offsetY=e.clientY-b.top;startX=e.clientX;startY=e.clientY;bird.style.transition='none';hint.textContent='Llevalo por el cielo…'};
  bird.onpointermove=e=>{if(!dragging)return;const r=scene.getBoundingClientRect();place(e.clientX-r.left-offsetX,e.clientY-r.top-offsetY)};
  bird.onpointerup=e=>{if(!dragging)return;dragging=false;bird.releasePointerCapture?.(e.pointerId);if(Math.hypot(e.clientX-startX,e.clientY-startY)<18){hint.textContent='Movelo un poquito y soltalo ✦';return}const b=bird.getBoundingClientRect(),word=document.createElement('div');word.className='word';word.textContent=phrases[found++];
const sceneRect = scene.getBoundingClientRect();
word.style.left = (e.clientX - sceneRect.left - 120) + 'px';
word.style.top = (e.clientY - sceneRect.top - 40) + 'px';
$('#words').append(word);
$('#words').append(word);setTimeout(()=>word.remove(),4300);if(found<phrases.length)hint.textContent=`Descubriste ${found} de ${phrases.length} frases ✦`;else{hint.textContent='El colibrí te dejó algo ✦';next.classList.add('show')}};
  next.onclick=()=>{show('#letterScene');setTimeout(open,350)};
}function open(){let e=$('#envelope');e.classList.add('open');setTimeout(letter,1150)}$('#envelope').onclick=open;function letter(){$('.stage').style.display='none';$('#letter').classList.add('show');type();petal();setTimeout(()=>$('#galleryBtn').classList.add('show'),7000)}function type(){let i=0,target=$('#type');function t(){if(i>=text.length)return;let c=text[i++];target.append(c==='\n'?document.createElement('br'):document.createTextNode(c));setTimeout(t,c==='.'?130:17)}t()}function petal(){petals=setInterval(()=>{let p=document.createElement('i');p.className='petal';p.style.left=Math.random()*100+'vw';p.style.setProperty('--x',(Math.random()*160-80)+'px');p.style.setProperty('--t',(5+Math.random()*4)+'s');$('#petalLayer').append(p);setTimeout(()=>p.remove(),10000)},450)}$('#galleryBtn').onclick=()=>show('#gallery');
$$('.polaroid').forEach((p,i)=>p.onclick=()=>{let m=$('#modal');m.classList.add('show');$('#modal div').style.backgroundImage=`url(img/foto-${i+1}.jpg),linear-gradient(135deg,#f5b6a5,#ffdfa9)`;$('#modal p').textContent=p.dataset.caption});$('#modal button').onclick=()=>$('#modal').classList.remove('show');$('#finalBtn').onclick=()=>{show('#final');heart()};$('#replay').onclick=()=>{cancelAnimationFrame(frame);show('#intro')};
function heart(){let c=$('#heart'),ctx=c.getContext('2d');function size(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}size();let dots=[];for(let i=0;i<430;i++){let t=Math.random()*Math.PI*2,r=.2+Math.random()*.8;dots.push([16*Math.sin(t)**3*r,-(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t))*r,Math.random()*2+1])}function draw(now){ctx.clearRect(0,0,innerWidth,innerHeight);let s=Math.min(innerWidth,innerHeight)*.017*(1+Math.sin(now/700)*.03);dots.forEach((d,i)=>{ctx.beginPath();ctx.fillStyle=`hsla(${(now/30+i)%360},90%,75%,.8)`;ctx.shadowBlur=10;ctx.shadowColor=ctx.fillStyle;ctx.arc(innerWidth/2+d[0]*s,innerHeight*.43+d[1]*s,d[2],0,7);ctx.fill()});frame=requestAnimationFrame(draw)}draw(0);setTimeout(()=>$('.finalcopy').classList.add('show'),1400)}
});